#! /bin/bash
set -e
if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
    source /mnt/d/solutions/ENVIRONMENTS/discord_env/bin/activate
else
    source ~/ENVIRONMENTS/discord_env/bin/activate
fi

for file in dm*.log; do mv "$file" "past_$file"; done;

nohup python bot.py > dm_$(date +%Y%m%d_%H%M%S).log 2>&1 &
echo $! > bot.pid
